support JIT compiler transform variant
Schleifner/asc-to-header pull request #18
Opened 2023-07-06 07:36 UTC by JesseCodeBones

2023-07-06 07:55 UTC, HerrCai0907 requested changes

2023-07-06 07:55 UTC, HerrCai0907 commented on fixture/asc1.ts.compiler.fixture.hpp
> +enum class Status16{
enum class Status16 : uint32_t

2023-07-06 07:55 UTC, HerrCai0907 commented on fixture/asc1.ts.compiler.fixture.hpp
> +
disable clang-format

2023-07-06 07:55 UTC, HerrCai0907 commented on fixture/asc1.ts.compiler.fixture.hpp
> +enum class Status10{
provide command option for namespace

2023-07-06 09:56 UTC, Changqing-JING approved these changes

2023-07-07 01:47 UTC, HerrCai0907 approved these changes

2023-07-07 02:05 UTC, merged